apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    {{- include "dummy-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dummy-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.resources.limits.nvidia.com.gpu }}
            requests:
              nvidia.com/gpu: {{ .Values.resources.requests.nvidia.com.gpu }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
